services:
  - type: web
    name: gdggug-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
